# Generated by Django 3.2.7 on 2021-09-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=64)),
                ('receiver', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_block', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('difficulty', models.FloatField()),
                ('nonce', models.IntegerField()),
                ('prev_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='chain.block')),
                ('transactions', models.ManyToManyField(related_name='block_transactions', to='chain.Transaction')),
            ],
        ),
    ]
