# Generated by Django 3.2.7 on 2021-09-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='prev_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chain.block'),
        ),
    ]
