# Generated by Django 3.2.7 on 2021-09-15 20:06

import chain.validators_block
import chain.validators_trx
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_alter_block_prev_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='difficulty',
            field=models.PositiveIntegerField(validators=[chain.validators_block.validate_difficulty]),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash_block',
            field=models.CharField(max_length=256, validators=[chain.validators_block.validate_hash_block]),
        ),
        migrations.AlterField(
            model_name='block',
            name='prev_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chain.block', validators=[chain.validators_block.validate_prev_block]),
        ),
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(validators=[chain.validators_block.validate_timestamp]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.CharField(max_length=64, validators=[chain.validators_trx.validate_receiver]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(max_length=64, validators=[chain.validators_trx.validate_sender]),
        ),
    ]
